FROM node:18-alpine
WORKDIR /app
ENV NODE_ENV=development
COPY package.json package-lock.json ./
RUN npm ci
# Instala nodemon globalmente si lo prefieres
RUN npm install -g nodemon
COPY . .
EXPOSE 3001
CMD ["nodemon", "--legacy-watch", "server.js"]
